### ISSUE TITLE
Add tests for growlog.cli

### ISSUE THREAD

**Issue by accraze** [open-source-botany/growlog#6]
There is currently only one test for the CLI:
https://github.com/open-source-botany/growlog/blob/master/tests/test_growlog.py#L23

This is very basic and only asserts that the cli runs and outputs some text.

There should be similar tests that make sure the following functionality works:
* [`new_crop`](https://github.com/open-source-botany/growlog/blob/master/src/growlog/cli.py#L49)
* [`update_crop`](https://github.com/open-source-botany/growlog/blob/master/src/growlog/cli.py#L67)
* [`delete_crop`](https://github.com/open-source-botany/growlog/blob/master/src/growlog/cli.py#L79)

Current Coverage:
https://codecov.io/gh/open-source-botany/growlog/src/master/src/growlog/cli.py

**Comment by SukiCZ** [comment]
Hi,
I would like to give you a help but I think the structure of the test case is not ideal. I would write separate test for loading and saving file with mocked file-system and a set of tests for rest of functionality with mocked `save_growlog` and `load_growlog` functions.
Sounds good to you?
Cheers :shirt:

**Comment by accraze** [comment]
Hey @SukiCZ that sounds like a great idea! I wanted to do something similar but never had the time to do it. Go for it :+1:

**Comment by accraze** [comment]
resolved by #8
